// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzziabjtxqlqafajowfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6emlhYmp0eHFscWFmYWpvd2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NDQ0NDAsImV4cCI6MjA4NTIyMDQ0MH0.p27T25EtFXi8yeGVTWMgmJgUk12e_zQ3qDwuT5niKwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});