// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttfoshdnyskcbjqeqbzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Zm9zaGRueXNrY2JqcWVxYnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjQ4ODUsImV4cCI6MjA3Mjg0MDg4NX0.eqsnGnA93eQHDpGIfpZuY3LaCxCgCh1JeEIY9F5xumA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});